ALTER TABLE bpw_recpmtinstruction ADD CONSTRAINT sys_c0052845 FOREIGN KEY (batchid) REFERENCES bpw_paymentbatch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product_i18n ADD CONSTRAINT fk_product__reference_product FOREIGN KEY (bank_id,product_id) REFERENCES product(bank_id,product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_recrecord ADD CONSTRAINT fk_achrecrcd_btid FOREIGN KEY (batchid) REFERENCES ach_recbatch(recbatchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ent_profile_info ADD CONSTRAINT sys_c0051521 FOREIGN KEY (profile_ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_filebatch ADD CONSTRAINT fk_filebatchfileid FOREIGN KEY (fileid) REFERENCES ach_file(fileid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE object_type_props ADD CONSTRAINT sys_c0051507 FOREIGN KEY (object_type) REFERENCES object_type(object_type) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE res_summary_txt ADD CONSTRAINT sys_c0051898 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE contact_points ADD CONSTRAINT fk_contact__reference_customer FOREIGN KEY (directory_id) REFERENCES customer(directory_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_transactions ADD CONSTRAINT sys_c0052019 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rpps_fiinfo ADD CONSTRAINT fk_rppsfi_fiid FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_lbtransactions ADD CONSTRAINT sys_c0052041 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entitlement_del ADD CONSTRAINT sys_c0051499 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE entitlement_del ADD CONSTRAINT sys_c0051500 FOREIGN KEY (operation_name) REFERENCES entitlement_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE entitlement_del ADD CONSTRAINT sys_c0051501 FOREIGN KEY (object_type) REFERENCES object_type(object_type) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE entitlement_del ADD CONSTRAINT sys_c0051502 FOREIGN KEY (member_type,member_subtype,member_id) REFERENCES entitlement_gmemb(member_type,member_subtype,member_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_record ADD CONSTRAINT fk_achrcd_btch_id FOREIGN KEY (batchid) REFERENCES ach_batch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE business_employee ADD CONSTRAINT sql031116112834330 FOREIGN KEY (directory_id) REFERENCES customer(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE business_employee ADD CONSTRAINT sql031116112834350 FOREIGN KEY (business_id) REFERENCES business(business_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rptsortcriteria ADD CONSTRAINT sys_c0051637 FOREIGN KEY (reportid) REFERENCES rptreport(reportid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_config ADD CONSTRAINT sys_c0052021 FOREIGN KEY (id) REFERENCES bs_fi(fiid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_ccacctsummary ADD CONSTRAINT sys_c0051696 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE limits ADD CONSTRAINT sys_c0051508 FOREIGN KEY (operation_name) REFERENCES limit_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE limits ADD CONSTRAINT sys_c0051511 FOREIGN KEY (object_type) REFERENCES object_type(object_type) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE limits ADD CONSTRAINT sys_c0051510 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE limits ADD CONSTRAINT sys_c0051509 FOREIGN KEY (member_type,member_subtype,member_id) REFERENCES entitlement_gmemb(member_type,member_subtype,member_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE req_appr ADD CONSTRAINT sys_c0052136 FOREIGN KEY (member_type,member_subtype,member_id) REFERENCES entitlement_gmemb(member_type,member_subtype,member_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE req_appr ADD CONSTRAINT sys_c0052138 FOREIGN KEY (object_type) REFERENCES object_type(object_type) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE req_appr ADD CONSTRAINT sys_c0052135 FOREIGN KEY (operation_name) REFERENCES req_appr_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE req_appr ADD CONSTRAINT sys_c0052137 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE customer_rel ADD CONSTRAINT f_c_rel_2 FOREIGN KEY (primary_user_id) REFERENCES customer(directory_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE customer_rel ADD CONSTRAINT f_c_rel_1 FOREIGN KEY (directory_id) REFERENCES customer(directory_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_xferinstruction ADD CONSTRAINT sys_c0052770 FOREIGN KEY (batchid) REFERENCES bpw_transferbatch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_mail ADD CONSTRAINT sys_c0052020 FOREIGN KEY (customerid) REFERENCES bs_customer(customerid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reg_transaction ADD CONSTRAINT sql031116112835050 FOREIGN KEY (directory_id,account_id) REFERENCES accounts(directory_id,account_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bank_employee ADD CONSTRAINT sql031116112834150 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE category ADD CONSTRAINT sql031116112834370 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE accounts ADD CONSTRAINT sql031116112833950 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_pmtinstruction ADD CONSTRAINT sys_c0052844 FOREIGN KEY (batchid) REFERENCES bpw_paymentbatch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE queue_members ADD CONSTRAINT sql031116112834920 FOREIGN KEY (employee_id) REFERENCES bank_employee(employee_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE queue_members ADD CONSTRAINT sql031116112834940 FOREIGN KEY (queue_id) REFERENCES queue(queue_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE mnthly_acct_smry ADD CONSTRAINT sys_c0051876 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_lbcredititems ADD CONSTRAINT sys_c0051741 FOREIGN KEY (dclockboxid) REFERENCES dc_lockbox(dclockboxid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE app_form ADD CONSTRAINT sql031116112834010 FOREIGN KEY (app_id) REFERENCES application(app_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE interest_summary ADD CONSTRAINT sys_c0051905 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etoe_btx_data ADD CONSTRAINT etoe_btx_data_session_fk FOREIGN KEY (etoe_session_id) REFERENCES etoe_session(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE status_i18n ADD CONSTRAINT fk_status_i_reference_status FOREIGN KEY (bank_id,status_id) REFERENCES status(bank_id,status_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_lockboxsummary ADD CONSTRAINT sys_c0051724 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE transactions ADD CONSTRAINT sys_c0051947 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_wireaddenda ADD CONSTRAINT sys_c0052394 FOREIGN KEY (srvrtid) REFERENCES bpw_wireinfo(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_location ADD CONSTRAINT fk_ccloc_compid FOREIGN KEY (compid) REFERENCES cc_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_flatfile ADD CONSTRAINT fk_achflatfile_id FOREIGN KEY (fileid) REFERENCES ach_file(fileid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_paymentbatch ADD CONSTRAINT sys_c0052842 FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_paymentbatch ADD CONSTRAINT sys_c0052843 FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE queue ADD CONSTRAINT sql031116112834890 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE application ADD CONSTRAINT sql031116112834080 FOREIGN KEY (form_id) REFERENCES form(form_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE application ADD CONSTRAINT sql031116112834050 FOREIGN KEY (bank_id,category_id) REFERENCES category(bank_id,category_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE application ADD CONSTRAINT sql031116112834130 FOREIGN KEY (bank_id,product_id,status_id) REFERENCES product_status(bank_id,product_id,status_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE application ADD CONSTRAINT sql031116112834100 FOREIGN KEY (bank_id,product_id) REFERENCES product(bank_id,product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE queue_i18n ADD CONSTRAINT fk_queue_i1_reference_queue FOREIGN KEY (queue_id) REFERENCES queue(queue_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE affil_cutoff_times ADD CONSTRAINT fk_affil_cu_sql036666_affil_cu FOREIGN KEY (affiliate_bank_id,cut_off_type) REFERENCES affil_cutoff_defn(affiliate_bank_id,cut_off_type) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE feature_type_props ADD CONSTRAINT sys_c0051555 FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE daily_bal_summary ADD CONSTRAINT sys_c0051940 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE customer ADD CONSTRAINT sql031116112834510 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE customer ADD CONSTRAINT sql031116112834490 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_customerroute ADD CONSTRAINT fk_bpw_cr_custid FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_customerroute ADD CONSTRAINT fk_bpw_cr_rtid FOREIGN KEY (routeid) REFERENCES bpw_fulfillment(routeid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_recwireinfo ADD CONSTRAINT sys_c0052404 FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rpps_payeeext ADD CONSTRAINT fk_billerrppsfiid FOREIGN KEY (rppsfiid) REFERENCES rpps_fiinfo(rppsfiid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_orcc_payee_mask ADD CONSTRAINT fk_orccpmsk_payid FOREIGN KEY (payeeid) REFERENCES bpw_payee(payeeid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_recxferextrainfo ADD CONSTRAINT fk_recxferxtrainfo FOREIGN KEY (recsrvrtid) REFERENCES bpw_recxferinstruction(recsrvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entitlement_feature ADD CONSTRAINT sys_c0051560 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE entitlement_feature ADD CONSTRAINT sys_c0051559 FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ent_type_props ADD CONSTRAINT sys_c0051505 FOREIGN KEY (operation_name) REFERENCES entitlement_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_lbcredititems ADD CONSTRAINT sys_c0052051 FOREIGN KEY (lockboxid) REFERENCES bs_lockbox(lockboxid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etf_achbatch ADD CONSTRAINT fk_etfbatchfileid FOREIGN KEY (fileid) REFERENCES etf_achfile(fileid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE da_category_details ADD CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES da_category(da_category_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE application_history ADD CONSTRAINT fk_app_history_app_id FOREIGN KEY (app_id) REFERENCES application(app_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tw_transdetail ADD CONSTRAINT sys_c0051622 FOREIGN KEY (twid) REFERENCES tw_transaction(twid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_wireinfo ADD CONSTRAINT sys_c0052387 FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_lockboxsummary ADD CONSTRAINT sys_c0052033 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etf_achentry ADD CONSTRAINT fk_etfbatchid FOREIGN KEY (batchid) REFERENCES etf_achbatch(batchid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sc_calendarassoc ADD CONSTRAINT fk_sc_calen_sccalenda_sc_calen FOREIGN KEY (calendar_id) REFERENCES sc_calendardefn(calendar_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reg_payee ADD CONSTRAINT sql031116112834980 FOREIGN KEY (reg_user_cat_id,directory_id) REFERENCES reg_user_category(reg_user_cat_id,directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reg_user_category ADD CONSTRAINT sql031116112835080 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_wirepayee ADD CONSTRAINT sys_c0052365 FOREIGN KEY (beneficiarybankid) REFERENCES bpw_wirebank(bankid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_account ADD CONSTRAINT sys_c0052015 FOREIGN KEY (accounttypeid) REFERENCES bs_accounttype(accounttypeid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bs_account ADD CONSTRAINT sys_c0052016 FOREIGN KEY (fiid) REFERENCES bs_fi(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_dsbsummary ADD CONSTRAINT sys_c0051748 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE alert_properties ADD CONSTRAINT fk_alert_pr_reference_user_ale FOREIGN KEY (alert_id) REFERENCES user_alerts(alert_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_employee ADD CONSTRAINT sys_c0052870 FOREIGN KEY (acctid) REFERENCES etf_externalacct(acctid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_pmtextrainfo ADD CONSTRAINT fk_bpw_pmtextrinfo FOREIGN KEY (srvrtid) REFERENCES bpw_pmtinstruction(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_batchtemplate ADD CONSTRAINT fk_achbttmp_comp FOREIGN KEY (compid) REFERENCES ach_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE customer_payee ADD CONSTRAINT sql031116112834530 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_batch ADD CONSTRAINT fk_achbatch_comp FOREIGN KEY (compid) REFERENCES ach_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product_status ADD CONSTRAINT sql031116112834870 FOREIGN KEY (bank_id,status_id) REFERENCES status(bank_id,status_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_status ADD CONSTRAINT sql031116112834850 FOREIGN KEY (bank_id,product_id) REFERENCES product(bank_id,product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_pmthist ADD CONSTRAINT fk_pmthist_stran FOREIGN KEY (srvrtid) REFERENCES bpw_srvrtrans(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_pmthist ADD CONSTRAINT fk_pmthist_stid FOREIGN KEY (srvrtid) REFERENCES bpw_pmtinstruction(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_dsbtransactions ADD CONSTRAINT sys_c0052064 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE status ADD CONSTRAINT sql031116112835110 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_payeeintrmdbnks ADD CONSTRAINT sys_c0052371 FOREIGN KEY (payeeid) REFERENCES bpw_wirepayee(payeeid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_payeeintrmdbnks ADD CONSTRAINT sys_c0052372 FOREIGN KEY (bankid) REFERENCES bpw_wirebank(bankid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_orcccustomercrossreference ADD CONSTRAINT fk_orcc_custid FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_transferbatch ADD CONSTRAINT sys_c0052767 FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_transferbatch ADD CONSTRAINT sys_c0052768 FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE appr_groupmembers ADD CONSTRAINT sys_c0051609 FOREIGN KEY (apprgroupid) REFERENCES appr_groups(apprgroupid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product ADD CONSTRAINT sql031116112834740 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product ADD CONSTRAINT sql031116112834770 FOREIGN KEY (form_id) REFERENCES form(form_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product ADD CONSTRAINT sql031116112834700 FOREIGN KEY (bank_id,category_id) REFERENCES category(bank_id,category_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE appr_flowchains ADD CONSTRAINT sys_c0051582 FOREIGN KEY (levelid) REFERENCES appr_flowlevels(levelid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_vendor ADD CONSTRAINT sys_c0052892 FOREIGN KEY (acctid) REFERENCES etf_externalacct(acctid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_companycutoff ADD CONSTRAINT fk_cccomp_cutoffid FOREIGN KEY (cutoffid) REFERENCES sch_cutoffs(cutoffid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cc_companycutoff ADD CONSTRAINT fk_cccomp_compid FOREIGN KEY (compid) REFERENCES cc_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_batchhist ADD CONSTRAINT fk_cc_bhist_compid FOREIGN KEY (compid) REFERENCES cc_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reg_tran_category ADD CONSTRAINT sql031116112835020 FOREIGN KEY (reg_transaction_id) REFERENCES reg_transaction(reg_transaction_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE reg_tran_category ADD CONSTRAINT sql031116112835000 FOREIGN KEY (reg_user_cat_id,directory_id) REFERENCES reg_user_category(reg_user_cat_id,directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tax_forms ADD CONSTRAINT sql031116112835140 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE da_category_limits ADD CONSTRAINT fk_category_limit_id FOREIGN KEY (category_id) REFERENCES da_category(da_category_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sc_holidaydefn ADD CONSTRAINT fk_sc_holid_sccalenda_sc_calen FOREIGN KEY (calendar_id) REFERENCES sc_calendardefn(calendar_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_dsbsummary ADD CONSTRAINT sys_c0052057 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reserve_summary ADD CONSTRAINT sys_c0051895 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_addenda ADD CONSTRAINT fk_achadnd_rcd_id FOREIGN KEY (recordid) REFERENCES ach_record(recordid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE form_columns_i18n ADD CONSTRAINT fk_form_col_reference_form_col FOREIGN KEY (form_id,field_id) REFERENCES form_columns(form_id,field_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE response_body ADD CONSTRAINT sql031116112835090 FOREIGN KEY (response_id) REFERENCES queue_response(response_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bank_mail ADD CONSTRAINT sql031116112834180 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_entry ADD CONSTRAINT fk_cc_entry_locid FOREIGN KEY (locationid) REFERENCES cc_location(locationid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_bankacct ADD CONSTRAINT fk_backacct_fiid FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product_access ADD CONSTRAINT sql031116112834820 FOREIGN KEY (employee_id) REFERENCES bank_employee(employee_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_access ADD CONSTRAINT sql031116112834800 FOREIGN KEY (bank_id,product_id) REFERENCES product(bank_id,product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sva_wallet ADD CONSTRAINT sva_wallet_fk_mobile_device_id FOREIGN KEY (mobile_device_id) REFERENCES mobile_device(device_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sva_wallet ADD CONSTRAINT sva_wallet_fk_directory_id FOREIGN KEY (directory_id) REFERENCES customer(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_transactionsdesc ADD CONSTRAINT sys_c0051689 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE information ADD CONSTRAINT sys_c0051879 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE int_bal_summary ADD CONSTRAINT sys_c0051924 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_xferextrainfo ADD CONSTRAINT fk_xferextrainfo FOREIGN KEY (srvrtid) REFERENCES bpw_xferinstruction(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ent_user_profiles ADD CONSTRAINT sys_c0051525 FOREIGN KEY (profile_ent_group_id) REFERENCES ent_profile_info(profile_ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_lockbox ADD CONSTRAINT sys_c0051717 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_transfer ADD CONSTRAINT sys_c0052769 FOREIGN KEY (batchid) REFERENCES bpw_transferbatch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_customeraccount ADD CONSTRAINT sys_c0052018 FOREIGN KEY (customerid) REFERENCES bs_customer(customerid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bs_customeraccount ADD CONSTRAINT sys_c0052017 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_recaddenda ADD CONSTRAINT fk_achrecadn_rdid FOREIGN KEY (recordid) REFERENCES ach_recrecord(recrecordid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_accountsummary ADD CONSTRAINT sys_c0051666 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE custom_ims_tag ADD CONSTRAINT sql031116112834420 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message ADD CONSTRAINT sql031116112834620 FOREIGN KEY (bank_id) REFERENCES bank(bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_wireinfo2 ADD CONSTRAINT sys_c0052390 FOREIGN KEY (srvrtid) REFERENCES bpw_wireinfo(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_company ADD CONSTRAINT fk_cccomp_custid FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sch_device_alert_message ADD CONSTRAINT f_device_id FOREIGN KEY (device_id) REFERENCES mobile_device(device_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_fileentry ADD CONSTRAINT fk_fileentrybatch FOREIGN KEY (batchid) REFERENCES ach_filebatch(batchid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_recwireaddenda ADD CONSTRAINT sys_c0052411 FOREIGN KEY (recsrvrtid) REFERENCES bpw_recwireinfo(recsrvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE directory_data ADD CONSTRAINT sql031116112834560 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE mobile_device_alert_settings ADD CONSTRAINT fk_mobiledevice_id FOREIGN KEY (device_id) REFERENCES mobile_device(device_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE message_item ADD CONSTRAINT sql031116112834670 FOREIGN KEY (message_id) REFERENCES message(message_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bs_lockbox ADD CONSTRAINT sys_c0052027 FOREIGN KEY (accountid) REFERENCES bs_account(accountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sc_default ADD CONSTRAINT fk_sc_defau_sccalenda_sc_calen FOREIGN KEY (calendar_id) REFERENCES sc_calendardefn(calendar_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_recbatch ADD CONSTRAINT fk_achrecbth_comp FOREIGN KEY (compid) REFERENCES ach_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE queue_response ADD CONSTRAINT sql031116112834960 FOREIGN KEY (queue_id) REFERENCES queue(queue_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bank_mail_message ADD CONSTRAINT sql031116112834200 FOREIGN KEY (directory_id,msg_id,mail_type) REFERENCES bank_mail(directory_id,msg_id,mail_type) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_payee ADD CONSTRAINT fk_achpay_compid FOREIGN KEY (compid) REFERENCES ach_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE feature ADD CONSTRAINT sys_c0051550 FOREIGN KEY (feature_group_id) REFERENCES feature_group(feature_group_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sch_temp_alert_message_cp ADD CONSTRAINT fk_cp_id FOREIGN KEY (contact_point_id) REFERENCES contact_points(contact_point_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entitlement_gmemb ADD CONSTRAINT sys_c0051498 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE accountgroup ADD CONSTRAINT fk_accountg_reference_business FOREIGN KEY (bus_directory_id) REFERENCES business(business_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE etoe_log ADD CONSTRAINT etoe_log_session_fk FOREIGN KEY (etoe_session_id) REFERENCES etoe_session(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rpps_pmtentrymap ADD CONSTRAINT fk_rppspmtstid FOREIGN KEY (srvrtid) REFERENCES bpw_pmtinstruction(srvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE rpps_pmtentrymap ADD CONSTRAINT fk_rppspmtfid FOREIGN KEY (fileid) REFERENCES rpps_pmtfilemap(fileid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE balance_summary ADD CONSTRAINT sys_c0051935 FOREIGN KEY (stmt_id) REFERENCES ints_statement(stmt_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE req_appr_props ADD CONSTRAINT sys_c0052132 FOREIGN KEY (operation_name) REFERENCES req_appr_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reg_user_category_budget ADD CONSTRAINT budget_fk_reg_user_cat FOREIGN KEY (reg_user_cat_id,directory_id) REFERENCES reg_user_category(reg_user_cat_id,directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_fixdepinstrment ADD CONSTRAINT sys_c0051712 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE oboprofile_jobtype ADD CONSTRAINT sys_c0051566 FOREIGN KEY (job_type_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE oboprofile_jobtype ADD CONSTRAINT sys_c0051565 FOREIGN KEY (obo_profile_id) REFERENCES entitlement_group(ent_group_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE global_msg_filters ADD CONSTRAINT fk_global_m_reference_global_m FOREIGN KEY (global_msg_id) REFERENCES global_message(global_msg_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_transactions ADD CONSTRAINT sys_c0051683 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_wirebatch ADD CONSTRAINT fk_wirebatch_cust FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_wirebatch ADD CONSTRAINT fk_wirebatch_fi FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_company ADD CONSTRAINT fk_achcomp_achfiid FOREIGN KEY (achfiid) REFERENCES ach_fiinfo(achfiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE ach_company ADD CONSTRAINT fk_achcomp_custid FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE account_alerts ADD CONSTRAINT fk_account__reference_user_ale FOREIGN KEY (alert_id) REFERENCES user_alerts(alert_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE br_bankreportdata ADD CONSTRAINT fk_br_bankr_bankrepor_br_bankr FOREIGN KEY (reportid) REFERENCES br_bankreports(reportid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_dsbtransactions ADD CONSTRAINT sys_c0051756 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE accountgroup_acct ADD CONSTRAINT fk_accountg_reference_accountg FOREIGN KEY (id) REFERENCES accountgroup(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_compoffsetacct ADD CONSTRAINT fk_ach_coa_acctid FOREIGN KEY (acctid) REFERENCES bpw_bankacct(acctid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE ach_compoffsetacct ADD CONSTRAINT fk_ach_coa_compid FOREIGN KEY (compid) REFERENCES ach_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE da_category ADD CONSTRAINT fk_da_item_id FOREIGN KEY (da_item_id) REFERENCES da_items(da_item_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE da_category ADD CONSTRAINT fk_da_category_id FOREIGN KEY (parent_id) REFERENCES da_category(da_category_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_extacctsummary ADD CONSTRAINT sys_c0051674 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE limit_type_props ADD CONSTRAINT sys_c0051506 FOREIGN KEY (operation_name) REFERENCES limit_list(operation_name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_recwireinfo2 ADD CONSTRAINT sys_c0052407 FOREIGN KEY (recsrvrtid) REFERENCES bpw_recwireinfo(recsrvrtid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_lbtransactions ADD CONSTRAINT sys_c0051733 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE running_total ADD CONSTRAINT sys_c0051504 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE running_total ADD CONSTRAINT sys_c0051503 FOREIGN KEY (limit_id) REFERENCES limits(limit_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rpps_pmtfilemap ADD CONSTRAINT fk_rppspmtfl_fiid FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE form_columns ADD CONSTRAINT sql031116112834590 FOREIGN KEY (form_id) REFERENCES form(form_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE mbk_sms_action ADD CONSTRAINT fk_smsaction_reqid FOREIGN KEY (request) REFERENCES mbk_sms_message(systemid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_smartsearch ADD CONSTRAINT fk_smtsrch_payid FOREIGN KEY (payeeid) REFERENCES bpw_payee(payeeid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cc_companyacct ADD CONSTRAINT fk_cc_comp_acctid FOREIGN KEY (acctid) REFERENCES bpw_bankacct(acctid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE cc_companyacct ADD CONSTRAINT fk_cc_comp_compid FOREIGN KEY (compid) REFERENCES cc_company(compid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_loanacctsummary ADD CONSTRAINT sys_c0051703 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sch_temp_alert_message ADD CONSTRAINT fk_device_id FOREIGN KEY (device_id) REFERENCES mobile_device(device_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE application_details ADD CONSTRAINT f_app_id FOREIGN KEY (app_id) REFERENCES application(app_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entitlement_gprops ADD CONSTRAINT sys_c0051497 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rptsearchcriteria ADD CONSTRAINT sys_c0051632 FOREIGN KEY (reportid) REFERENCES rptreport(reportid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_batches ADD CONSTRAINT fk_achbatches_cust FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE fi_fielddefn ADD CONSTRAINT sys_c0051832 FOREIGN KEY (mappingid) REFERENCES fi_mappingdefn(mappingid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE bpw_processwindow ADD CONSTRAINT sys_c0052734 FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE bpw_processwindow ADD CONSTRAINT sys_c0052735 FOREIGN KEY (customerid) REFERENCES bpw_customer(customerid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ach_fiinfo ADD CONSTRAINT fk_achfi_fiid FOREIGN KEY (fiid) REFERENCES bpw_fiinfo(fiid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entitlement_admin ADD CONSTRAINT sys_c0051496 FOREIGN KEY (ent_group_id) REFERENCES entitlement_group(ent_group_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE business ADD CONSTRAINT sql031116112834240 FOREIGN KEY (affiliate_bank_id) REFERENCES affiliate_bank(affiliate_bank_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE business ADD CONSTRAINT sql031116112834280 FOREIGN KEY (directory_id) REFERENCES customer_directory(directory_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE business ADD CONSTRAINT sql031116112834300 FOREIGN KEY (contact_id) REFERENCES contact_info(contact_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dc_accounthistory ADD CONSTRAINT sys_c0051659 FOREIGN KEY (dcaccountid) REFERENCES dc_account(dcaccountid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rptoptions ADD CONSTRAINT sys_c0051628 FOREIGN KEY (reportid) REFERENCES rptreport(reportid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE da_items ADD CONSTRAINT fk_business_id FOREIGN KEY (business_id) REFERENCES business(business_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE fx_rate ADD CONSTRAINT sys_c0051848 FOREIGN KEY (basecurrencycode) REFERENCES fx_currency(currencycode) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE fx_rate ADD CONSTRAINT sys_c0051849 FOREIGN KEY (targetcurrencycode) REFERENCES fx_currency(currencycode) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE global_message_i18n ADD CONSTRAINT f_global_messages FOREIGN KEY (global_msg_id) REFERENCES global_message(global_msg_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
