apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvY2IuZG9ja2VyLnJlcG9zaXRvcmllcy5zYXAub25kZW1hbmQuY29tIjp7InVzZXJuYW1lIjoib2NiX2RldmVsb3BlciIsInBhc3N3b3JkIjoiT2NiQGs4cyIsImVtYWlsIjoicy5iaG9zYWxlQHNhcC5jb20iLCJhdXRoIjoiYjJOaVgyUmxkbVZzYjNCbGNqcFBZMkpBYXpoeiJ9fX0=
kind: Secret
metadata:
  name: ocb-docker-artifactory
type: kubernetes.io/dockerconfigjson