/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.EnforcedLimitDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgentEnforcedLimitApi
 */
@Ignore
public class AgentEnforcedLimitApiTest {

    private final AgentEnforcedLimitApi api = new AgentEnforcedLimitApi();

    
    /**
     * Fetching Agent Enforced Limit
     *
     * Returns Agent Enforced Limit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAgentEnforcedLimitsTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String agentNumber = null;
        EnforcedLimitDetails response = api.getAgentEnforcedLimits(userId, userType, dataRoleId, roleId, agentNumber);

        // TODO: test validations
    }
    
    /**
     * Update Enforced Limits for an agent associated with Merchant
     *
     * Modify Enforced Limits
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAgentEnforcedLimitsTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String userName = null;
        String agentNumber = null;
        List<EnforcedLimitDetails> enforcedLimitDetails = null;
        EnforcedLimitDetails response = api.updateAgentEnforcedLimits(userId, userType, dataRoleId, roleId, userName, agentNumber, enforcedLimitDetails);

        // TODO: test validations
    }
    
}
