/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.AuthorisationResponse;
import com.worldpay.bna.onboarding.services.model.Authorisations;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthorisationApi
 */
@Ignore
public class AuthorisationApiTest {

    private final AuthorisationApi api = new AuthorisationApi();

    
    /**
     * get Authorisation
     *
     * Returns Authorisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthorisationTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Long authorisationId = null;
        AuthorisationResponse response = api.getAuthorisation(userId, userType, dataRoleId, roleId, authorisationId);

        // TODO: test validations
    }
    
    /**
     * Find Authorisation List
     *
     * Returns Authorisation List
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthorisationsTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String fromDate = null;
        String toDate = null;
        String cardNumber = null;
        String terminalId = null;
        String agentNumber = null;
        String type = null;
        String responseCode = null;
        Authorisations response = api.getAuthorisations(userId, userType, dataRoleId, roleId, fromDate, toDate, cardNumber, terminalId, agentNumber, type, responseCode);

        // TODO: test validations
    }
    
    /**
     * Find Records of Authorisation List in csv Format File
     *
     * Returns Records of Authorisation List in csv File
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthorisationsExportTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String fromDate = null;
        String toDate = null;
        String cardNumber = null;
        String terminalId = null;
        String agentNumber = null;
        String type = null;
        String responseCode = null;
        File response = api.getAuthorisationsExport(userId, userType, dataRoleId, roleId, fromDate, toDate, cardNumber, terminalId, agentNumber, type, responseCode);

        // TODO: test validations
    }
    
}
