/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.BnaApiResponse;
import com.worldpay.bna.onboarding.services.model.ChangeMerchantAuthentication;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChangeMerchantAuthenticationApi
 */
@Ignore
public class ChangeMerchantAuthenticationApiTest {

    private final ChangeMerchantAuthenticationApi api = new ChangeMerchantAuthenticationApi();

    
    /**
     * change password for merchant
     *
     * change merchant Authentication
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changeMerchantAuthenticationTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        ChangeMerchantAuthentication changeMerchantAuthentication = null;
        BnaApiResponse response = api.changeMerchantAuthentication(userId, userType, dataRoleId, roleId, changeMerchantAuthentication);

        // TODO: test validations
    }
    
}
