/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.FinancialControlRecordResponse;
import com.worldpay.bna.onboarding.services.model.FinancialControlRecords;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FinancialControlRecordApi
 */
@Ignore
public class FinancialControlRecordApiTest {

    private final FinancialControlRecordApi api = new FinancialControlRecordApi();

    
    /**
     * Get Financial Control Record by using FcrId.
     *
     * Returns Financial Control Record
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFinancialControlRecordTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Integer fcrId = null;
        FinancialControlRecordResponse response = api.getFinancialControlRecord(userId, userType, dataRoleId, roleId, fcrId);

        // TODO: test validations
    }
    
    /**
     * List Financial Control Record by using following filters like - TerminalId, AgentNumber, FCRId, Status, fromDate, toDate.
     *
     * Returns Financial Control Record List
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFinancialControlRecordsTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String fromDate = null;
        String toDate = null;
        String agentNumber = null;
        String terminalId = null;
        Integer fcrId = null;
        String status = null;
        FinancialControlRecords response = api.getFinancialControlRecords(userId, userType, dataRoleId, roleId, fromDate, toDate, agentNumber, terminalId, fcrId, status);

        // TODO: test validations
    }
    
}
