/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.PinPadList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PinPadApi
 */
@Ignore
public class PinPadApiTest {

    private final PinPadApi api = new PinPadApi();

    
    /**
     * List  of PinPads
     *
     * Returns List of PinPad
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPinPadTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String providerName = null;
        String modelName = null;
        String applicationType = null;
        String productType = null;
        PinPadList response = api.getPinPad(userId, userType, dataRoleId, roleId, providerName, modelName, applicationType, productType);

        // TODO: test validations
    }
    
}
