/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.RegionListResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegionApi
 */
@Ignore
public class RegionApiTest {

    private final RegionApi api = new RegionApi();

    
    /**
     * Find regions by using country code
     *
     * Returns region detail
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRegionDetailsTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String countryCode = null;
        Integer regionId = null;
        String regionNumber = null;
        RegionListResponse response = api.getRegionDetails(userId, userType, dataRoleId, roleId, countryCode, regionId, regionNumber);

        // TODO: test validations
    }
    
}
