/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.ServiceProviderEpos;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceprovidereposApi
 */
@Ignore
public class ServiceprovidereposApiTest {

    private final ServiceprovidereposApi api = new ServiceprovidereposApi();

    
    /**
     * Add service provider epos in system
     *
     * Returns status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addServiceProviderEposTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String userId2 = null;
        ServiceProviderEpos serviceProviderEpos = null;
        ServiceProviderEpos response = api.addServiceProviderEpos(userId, userType, dataRoleId, roleId, userId2, serviceProviderEpos);

        // TODO: test validations
    }
    
}
