/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.ServiceFeeTypeList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceFeeTypeApi
 */
@Ignore
public class ServiceFeeTypeApiTest {

    private final ServiceFeeTypeApi api = new ServiceFeeTypeApi();

    
    /**
     * Get Service fee type List
     *
     * Returns Array of Service fee type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServiceFeeTypeTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String code = null;
        String feeName = null;
        Integer serviceId = null;
        String type = null;
        String period = null;
        ServiceFeeTypeList response = api.getServiceFeeType(userId, userType, dataRoleId, roleId, code, feeName, serviceId, type, period);

        // TODO: test validations
    }
    
}
