/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.ServiceList;
import com.worldpay.bna.onboarding.services.model.ServiceProviderList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceApi
 */
@Ignore
public class ServiceApiTest {

    private final ServiceApi api = new ServiceApi();

    
    /**
     * Fetching Services (Acquirers)
     *
     * Returns Services (Acquirers)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServiceTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Integer id = null;
        String serviceProviderCode = null;
        String serviceName = null;
        String startDate = null;
        String mode = null;
        Integer uiQueryType = null;
        String mscSupported = null;
        String merchantNumber = null;
        ServiceList response = api.getService(userId, userType, dataRoleId, roleId, id, serviceProviderCode, serviceName, startDate, mode, uiQueryType, mscSupported, merchantNumber);

        // TODO: test validations
    }
    
    /**
     * Fetching Services Names
     *
     * Returns Service Names
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServiceNamesTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String cardIssuerCode = null;
        ServiceProviderList response = api.getServiceNames(userId, userType, dataRoleId, roleId, cardIssuerCode);

        // TODO: test validations
    }
    
}
