/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.TerminalAttributeResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TerminalattributeApi
 */
@Ignore
public class TerminalattributeApiTest {

    private final TerminalattributeApi api = new TerminalattributeApi();

    
    /**
     * Get Terminal Attribute
     *
     * Returns Terminal Attribute
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTerminalAttributeTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Boolean contactlessMagstripe11 = null;
        Boolean contactlessEMV12 = null;
        Boolean reservedForUK13 = null;
        Boolean reservedForUK14 = null;
        Boolean partialApprovalResSup21 = null;
        Boolean transactionIdentifiersSup22 = null;
        Boolean alternateCardNumberSup23 = null;
        Boolean reservedForUK24 = null;
        Boolean contactlessSignature31 = null;
        Boolean contactlessCDCVM32 = null;
        Boolean reservedForUK33 = null;
        Boolean reservedForUK34 = null;
        Boolean mPOSIntegratedCardReader41 = null;
        Boolean mPOSSeparateCardReader42 = null;
        Boolean reservedForUK43 = null;
        Boolean reservedForUK44 = null;
        Boolean reservedForUK51 = null;
        Boolean reservedForUK52 = null;
        Boolean reservedForUK53 = null;
        Boolean reservedForUK54 = null;
        Boolean reservedForUK61 = null;
        Boolean reservedForUK62 = null;
        Boolean reservedForUK63 = null;
        Boolean reservedForUK64 = null;
        TerminalAttributeResponse response = api.getTerminalAttribute(userId, userType, dataRoleId, roleId, contactlessMagstripe11, contactlessEMV12, reservedForUK13, reservedForUK14, partialApprovalResSup21, transactionIdentifiersSup22, alternateCardNumberSup23, reservedForUK24, contactlessSignature31, contactlessCDCVM32, reservedForUK33, reservedForUK34, mPOSIntegratedCardReader41, mPOSSeparateCardReader42, reservedForUK43, reservedForUK44, reservedForUK51, reservedForUK52, reservedForUK53, reservedForUK54, reservedForUK61, reservedForUK62, reservedForUK63, reservedForUK64);

        // TODO: test validations
    }
    
}
