/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.TerminalProfileArrayResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TerminalprofilesApi
 */
@Ignore
public class TerminalprofilesApiTest {

    private final TerminalprofilesApi api = new TerminalprofilesApi();

    
    /**
     * Find Terminal Profiles
     *
     * Returns Terminal Profiles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTerminalProfilesTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Integer terminalProfileId = null;
        String terminalProfileName = null;
        TerminalProfileArrayResponse response = api.getTerminalProfiles(userId, userType, dataRoleId, roleId, terminalProfileId, terminalProfileName);

        // TODO: test validations
    }
    
}
