/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.TokenPolicy;
import com.worldpay.bna.onboarding.services.model.TokenPolicyResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokenpoliciesApi
 */
@Ignore
public class TokenpoliciesApiTest {

    private final TokenpoliciesApi api = new TokenpoliciesApi();

    
    /**
     * Add a new Token Policy to the portal
     *
     * Add a new Token Policy to the portal
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTokenPolicyTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        TokenPolicy tokenPolicy = null;
        TokenPolicyResponse response = api.addTokenPolicy(userId, userType, dataRoleId, roleId, tokenPolicy);

        // TODO: test validations
    }
    
    /**
     * Fetching Token Policies
     *
     * Returns Token Policies
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenPoliciesTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        Integer tokenIdentifier = null;
        String customerCode = null;
        TokenPolicyResponse response = api.getTokenPolicies(userId, userType, dataRoleId, roleId, tokenIdentifier, customerCode);

        // TODO: test validations
    }
    
}
