/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.TransactionBand;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionBandApi
 */
@Ignore
public class TransactionBandApiTest {

    private final TransactionBandApi api = new TransactionBandApi();

    
    /**
     * Get Transaction Band
     *
     * transaction Band list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTransactionBandTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        String entityType = null;
        String productPlanCode = null;
        TransactionBand response = api.getTransactionBand(userId, userType, dataRoleId, roleId, entityType, productPlanCode);

        // TODO: test validations
    }
    
}
