/*
 * Swagger Onboarding
 * This API provides REST end points for Boarding of customer into system.
 *
 * OpenAPI spec version: 8.1.0
 * Contact: DL-WPT-Lords-Of-Code@worldpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldpay.bna.onboarding.services;

import com.worldpay.bna.onboarding.services.invoker.ApiException;
import com.worldpay.bna.onboarding.services.model.BnaApiResponse;
import com.worldpay.bna.onboarding.services.model.UpdateUUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UpdateUuidFromMidApi
 */
@Ignore
public class UpdateUuidFromMidApiTest {

    private final UpdateUuidFromMidApi api = new UpdateUuidFromMidApi();

    
    /**
     * update UUID from MID
     *
     * update UUID from MID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUUIDTest() throws ApiException {
        String userId = null;
        String userType = null;
        String dataRoleId = null;
        Integer roleId = null;
        UpdateUUID updateUUID = null;
        BnaApiResponse response = api.updateUUID(userId, userType, dataRoleId, roleId, updateUUID);

        // TODO: test validations
    }
    
}
